name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  CLIP-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.15]
        pytorch-version: [1.12.1]
        include:
          - python-version: 3.8.15
            pytorch-version: 1.12.1
            torchvision-version: 0.13.1
    steps:
      - uses: conda-incubator/setup-miniconda@v2
      - run: conda install -n test python=${{ matrix.python-version }} pytorch=${{ matrix.pytorch-version }} torchvision=${{ matrix.torchvision-version }} cpuonly -c pytorch
      - uses: actions/checkout@v2
      - run: echo "$CONDA/envs/test/bin" >> $GITHUB_PATH
      - run: pip install pytest
      - run: pip install -r requirements.txt
